site_name: Pronochain
site_description: Documentation pour le projet Pronochain et ses solutions.
site_author: Pronochain

# Theme configuration
theme:
  name: material
  palette:
    scheme: pronochain
  language: fr
  features:
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css

# Customization
extra:
  search:
    language: "en, fr"
  social:
    - icon: fontawesome/brands/twitter
      link: https://mobile.twitter.com/pronochain
  generator: false
copyright: Copyright &copy; 2021 - 2022 Pronochain

# Extensions
markdown_extensions:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.emoji
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Accueil: index.md
  - Global:
    - Configuration:
      - Documentation: global/configuration/documentation.md
  - Génération NFT:
    - Initialisation: generation_nft/index.md
    - Configuration:
      - Variables d'environnements: generation_nft/configuration/variables_environnements.md
      - Pre-commit: generation_nft/configuration/pre_commit.md
      - Visual Studio Code: generation_nft/configuration/vs_code.md
    - Python:
      - Architecture: generation_nft/python/architecture.md
      - Packages: generation_nft/python/packages.md
      - Tests: generation_nft/python/tests.md
      - Règles et nomenclatures: generation_nft/python/regles.md
      - Logging: generation_nft/python/logging.md
    - Fonctionnalités:
      - Détection d'un visage: generation_nft/fonctionnalites/face_detect.md
      - Masques du visage: generation_nft/fonctionnalites/face_landmarks.md
      - Alignement du visage: generation_nft/fonctionnalites/face_aligner.md
      - Direction du visage: generation_nft/fonctionnalites/tilt_learning.md
      - Récupération des parties du visage: generation_nft/fonctionnalites/face_parsing.md
  - API:
    - Configuration:
        - Husky: api/configuration/husky.md
        - PhpCsFixer: api/configuration/php_cs_fixer.md
        - Lint Staged: api/configuration/lint_staged.md
        - Commitlint: api/configuration/commitlint.md
        - Standard Version: api/configuration/standard_version.md
